name: Deploy to Google Cloud
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: .
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: install libraries
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: build
      run: npm run build
    - name: deploy
      run: gcloud functions deploy discordDigest --runtime nodejs16 --region=europe-west1 --trigger-http --project discord-digest --set-env-vars DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }},DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }},DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}
